### ISSUE TITLE
scons problem: "TypeError : 'map' object is not subscriptable"

### ISSUE THREAD

**Issue by nakadachi** [harrylee365/pcmcsim_public#2]
scons: *** [obj_fast/AITManager/AITManager.fo] TypeError : 'map' object is not subscriptable
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/SCons/Subst.py", line 456, in substitute
    result = _dollar_exps.sub(sub_match, args)
  File "/usr/lib/python3/dist-packages/SCons/Subst.py", line 455, in sub_match
    return self.conv(self.expand(match.group(1), lvars))
  File "/usr/lib/python3/dist-packages/SCons/Subst.py", line 417, in expand
    return self.substitute(s, lv)
  File "/usr/lib/python3/dist-packages/SCons/Subst.py", line 473, in substitute
    return self.expand(args, lvars)
  File "/usr/lib/python3/dist-packages/SCons/Subst.py", line 428, in expand
    s = s(target=lvars['TARGETS'],
  File "/home/pcmcsim_public/SConstruct", line 138, in __call__
    split_src = srcs[0].split("/")
TypeError: 'map' object is not subscriptable

**Comment by harrylee365** [comment]
resolved
